[build]
  base = "IntuneAssistant.Docs"
  command = "npm run build"
  publish = "IntuneAssistant.Docs/.next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "18"